[build]
  base = "innovations-sub-app"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/immersive/*"
  to = "/immersive/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/orders/*"
  to = "/.netlify/functions/orders"
  status = 200
  force = false

[[redirects]]
  from = "/payments/*"
  to = "/.netlify/functions/payments"
  status = 200
  force = false

[[redirects]]
  from = "/events/*"
  to = "/.netlify/functions/events"
  status = 200
  force = false

[[redirects]]
  from = "/webhooks/stripe"
  to = "/.netlify/functions/stripeWebhook"
  status = 200
  force = false
